import { useState, useEffect } from "react";
import { Copy, KeyRound, Loader2, PlugZap, Shield, ShieldOff, Unplug } from "lucide-react";
import { api } from "../lib/api.js";

export default function VPNPanel() {
  const [status, setStatus] = useState(null);
  const [config, setConfig] = useState("");
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);

  async function refreshStatus() {
    try {
      const data = await api.vpnStatus();
      setStatus(data);
    } catch (err) {
      setStatus({ error: err.message, builtin: null, connected: false });
    }
  }

  useEffect(() => {
    refreshStatus();
  }, []);

  const builtin = status?.builtin;
  const connected = Boolean(status?.connected || builtin?.status === "active");
  const mode = status?.mode || "system-builtin";

  async function fetchConfig() {
    setLoading(true);
    try {
      const data = await api.vpnConfig();
      setConfig(data.client_config || data.config || "");
      if (!config && data?.public_key) {
        setConfig(`# NOVA system tunnel ${data.mode || ""}\n# Public key: ${data.public_key}\n# Listen port: ${data.listen_port}\n# Net: ${data.net}\n\n# Import the full client config below on the phone:\n`);
      }
    } catch (err) {
      setStatus({ ...status, error: err.message });
    } finally {
      setLoading(false);
    }
  }

  async function connect() {
    setLoading(true);
    try {
      await api.vpnConnect("", "wireguard");
      await refreshStatus();
    } catch (err) {
      setStatus({ ...status, error: err.message });
    } finally {
      setLoading(false);
    }
  }

  async function disconnect() {
    setLoading(true);
    try {
      await api.vpnDisconnect("builtin", "builtin");
      setConfig("");
      await refreshStatus();
    } catch (err) {
      setStatus({ ...status, error: err.message });
    } finally {
      setLoading(false);
    }
  }

  async function copyConfig() {
    if (!config) return;
    try {
      await navigator.clipboard.writeText(config);
      setCopied(true);
      setTimeout(() => setCopied(false), 1600);
    } catch (e) {
      // clipboard unavailable
    }
  }

  return (
    <section className="panel vpn-panel">
      <div className="panel-title">
        <span>VPN</span>
        {connected ? <Shield size={15} className="status-ok" /> : <ShieldOff size={15} />}
      </div>

      <div className={`vpn-banner ${connected ? "vpn-banner-ok" : "vpn-banner-off"}`}>
        <div className="vpn-banner-title">
          {connected ? <PlugZap size={14} /> : <Unplug size={14} />}
          SYSTEM VPN — {connected ? "CONNECTED" : "OFFLINE"}
        </div>
        <div className="muted" style={{ fontSize: 10 }}>
          {mode === "system-builtin"
            ? "Built into the platform — no external VPN vendor, keypair generated by the backend, devices join by importing the config."
            : "External tunnel active (wg/openvpn)."}
        </div>
      </div>

      <div className="vpn-status">
        <div className="status-row">
          <span>Transport</span>
          <code>{builtin?.transport || "nova-encrypted-wg"}</code>
        </div>
        <div className="status-row">
          <span>Listen port</span>
          <code>{builtin?.listen_port || 51820}</code>
        </div>
        <div className="status-row">
          <span>Net</span>
          <code>{builtin?.net || "10.66.0.0/24"}</code>
        </div>
        <div className="status-row">
          <span>Server Public Key</span>
          <code className="vpn-key">{builtin?.public_key || "pending"}</code>
        </div>
        {status?.wireguard?.interfaces?.length > 0 && (
          <div className="status-row">
            <span>External wg iface</span>
            <code>{status.wireguard.interfaces.map((i) => i.name).join(", ") || "—"}</code>
          </div>
        )}
      </div>

      <div className="tool-controls">
        <div className="target-row">
          <button className="command-button" onClick={fetchConfig} disabled={loading}>
            {loading ? <Loader2 size={13} className="spin" /> : <KeyRound size={13} />} GET CLIENT CONFIG
          </button>
          <button className="command-button" onClick={connect} disabled={loading || connected}>
            CONNECT
          </button>
          <button className="command-button command-button-danger" onClick={disconnect} disabled={loading || !connected}>
            DISCONNECT
          </button>
        </div>
      </div>

      {config && (
        <div className="vpn-config-box">
          <div className="scan-meta-row">
            <span>Phone/device WireGuard config</span>
            <button className="btn-sm" onClick={copyConfig} type="button">
              <Copy size={10} /> {copied ? "Copied!" : "Copy"}
            </button>
          </div>
          <textarea readOnly value={config} rows={12} spellCheck={false} />
        </div>
      )}

      {status?.error && <div className="inline-error">{status.error}</div>}
      <button className="icon-button refresh-btn" onClick={refreshStatus}>REFRESH</button>
    </section>
  );
}